// Code generated by MockGen. DO NOT EDIT.
// Source: web/business/userBusiness.go

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	dto "github.com/TulioGuaraldoB/q2-payer-challenge/web/dto"
	model "github.com/TulioGuaraldoB/q2-payer-challenge/web/model"
	gomock "github.com/golang/mock/gomock"
)

// MockIUserBusiness is a mock of IUserBusiness interface.
type MockIUserBusiness struct {
	ctrl     *gomock.Controller
	recorder *MockIUserBusinessMockRecorder
}

// MockIUserBusinessMockRecorder is the mock recorder for MockIUserBusiness.
type MockIUserBusinessMockRecorder struct {
	mock *MockIUserBusiness
}

// NewMockIUserBusiness creates a new mock instance.
func NewMockIUserBusiness(ctrl *gomock.Controller) *MockIUserBusiness {
	mock := &MockIUserBusiness{ctrl: ctrl}
	mock.recorder = &MockIUserBusinessMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIUserBusiness) EXPECT() *MockIUserBusinessMockRecorder {
	return m.recorder
}

// CreateUser mocks base method.
func (m *MockIUserBusiness) CreateUser(user *model.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser", user)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockIUserBusinessMockRecorder) CreateUser(user interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*MockIUserBusiness)(nil).CreateUser), user)
}

// DeleteUser mocks base method.
func (m *MockIUserBusiness) DeleteUser(userId uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteUser", userId)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteUser indicates an expected call of DeleteUser.
func (mr *MockIUserBusinessMockRecorder) DeleteUser(userId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteUser", reflect.TypeOf((*MockIUserBusiness)(nil).DeleteUser), userId)
}

// GetAllUsers mocks base method.
func (m *MockIUserBusiness) GetAllUsers() ([]model.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllUsers")
	ret0, _ := ret[0].([]model.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllUsers indicates an expected call of GetAllUsers.
func (mr *MockIUserBusinessMockRecorder) GetAllUsers() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllUsers", reflect.TypeOf((*MockIUserBusiness)(nil).GetAllUsers))
}

// GetUserByCpf mocks base method.
func (m *MockIUserBusiness) GetUserByCpf(userCpf string) (*model.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByCpf", userCpf)
	ret0, _ := ret[0].(*model.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByCpf indicates an expected call of GetUserByCpf.
func (mr *MockIUserBusinessMockRecorder) GetUserByCpf(userCpf interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByCpf", reflect.TypeOf((*MockIUserBusiness)(nil).GetUserByCpf), userCpf)
}

// GetUserByCredentials mocks base method.
func (m *MockIUserBusiness) GetUserByCredentials(userCredentials *dto.UserCredentials) (*model.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByCredentials", userCredentials)
	ret0, _ := ret[0].(*model.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByCredentials indicates an expected call of GetUserByCredentials.
func (mr *MockIUserBusinessMockRecorder) GetUserByCredentials(userCredentials interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByCredentials", reflect.TypeOf((*MockIUserBusiness)(nil).GetUserByCredentials), userCredentials)
}

// GetUserByEmail mocks base method.
func (m *MockIUserBusiness) GetUserByEmail(userEmail string) (*model.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByEmail", userEmail)
	ret0, _ := ret[0].(*model.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByEmail indicates an expected call of GetUserByEmail.
func (mr *MockIUserBusinessMockRecorder) GetUserByEmail(userEmail interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByEmail", reflect.TypeOf((*MockIUserBusiness)(nil).GetUserByEmail), userEmail)
}

// GetUserById mocks base method.
func (m *MockIUserBusiness) GetUserById(userId uint) (*model.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserById", userId)
	ret0, _ := ret[0].(*model.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserById indicates an expected call of GetUserById.
func (mr *MockIUserBusinessMockRecorder) GetUserById(userId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserById", reflect.TypeOf((*MockIUserBusiness)(nil).GetUserById), userId)
}
