definitions:
  dto.UserCredentials:
    properties:
      email:
        type: string
      password:
        type: string
    type: object
  dto.UserResponse:
    properties:
      cnpj:
        type: string
      cpf:
        type: string
      email:
        type: string
      full_name:
        type: string
      id:
        type: integer
      user_type:
        type: integer
    type: object
info:
  contact: {}
paths:
  /api/v1/user:
    get:
      consumes:
      - application/json
      description: Get All Users
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/dto.UserResponse'
            type: array
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      summary: Get All Users
      tags:
      - Get All Users
  /api/v1/user/:id:
    get:
      consumes:
      - application/json
      description: Get User By Id
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.UserResponse'
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      summary: Get User By Id
      tags:
      - Get User By Id
  /api/v1/user/cpf/:cpf:
    get:
      consumes:
      - application/json
      description: Get User By Cpf
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.UserResponse'
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      summary: Get User By Cpf
      tags:
      - Get User By Cpf
  /api/v1/user/email/:email:
    get:
      consumes:
      - application/json
      description: Get User By Email
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.UserResponse'
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      summary: Get User By Email
      tags:
      - Get User By Email
  /api/v1/user/login:
    post:
      consumes:
      - application/json
      description: Get User By Credentials
      parameters:
      - description: User Credentials
        in: body
        name: Credentials
        required: true
        schema:
          $ref: '#/definitions/dto.UserCredentials'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.UserResponse'
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      summary: Get User By Credentials
      tags:
      - Get User By Credentials
swagger: "2.0"
